--------------------------------------------------------
--  파일이 생성됨 - 목요일-8월-31-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCT_IMG
--------------------------------------------------------

  CREATE TABLE "TICKET"."PRODUCT_IMG" 
   (	"PRODUCT_NO" NUMBER, 
	"POSTER_NAME" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"DETAIL1_NAME" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"DETAIL2_NAME" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"DETAIL3_NAME" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"DETAIL4_NAME" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"DETAIL5_NAME" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"IMAGE_PATH" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "TICKET"."PRODUCT_IMG"."PRODUCT_NO" IS '상품번호';
   COMMENT ON COLUMN "TICKET"."PRODUCT_IMG"."POSTER_NAME" IS '포스터 이름';
   COMMENT ON COLUMN "TICKET"."PRODUCT_IMG"."DETAIL1_NAME" IS '상세1 이름';
   COMMENT ON COLUMN "TICKET"."PRODUCT_IMG"."DETAIL2_NAME" IS '상세2 이름';
   COMMENT ON COLUMN "TICKET"."PRODUCT_IMG"."DETAIL3_NAME" IS '상세3 이름';
   COMMENT ON COLUMN "TICKET"."PRODUCT_IMG"."DETAIL4_NAME" IS '상세4 이름';
   COMMENT ON COLUMN "TICKET"."PRODUCT_IMG"."DETAIL5_NAME" IS '상세5 이름';
   COMMENT ON COLUMN "TICKET"."PRODUCT_IMG"."IMAGE_PATH" IS '이미지 경로';
REM INSERTING into TICKET.PRODUCT_IMG
SET DEFINE OFF;
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (3,'작품전시_포스터_2023 청주공예비엔날레 (CHEONGJU CRAFT BIENNALE 2023).jpg','작품전시_상세1_2023 청주공예비엔날레 (CHEONGJU CRAFT BIENNALE 2023).jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (10,'작품전시_포스터_국립낙동강생물자원관.jpg','작품전시_상세1_국립낙동강생물자원관.jpg','작품전시_상세2_국립낙동강생물자원관.jpg','작품전시_상세3_국립낙동강생물자원관.jpg','작품전시_상세4_국립낙동강생물자원관.jpg','작품전시_상세5_국립낙동강생물자원관.jpg','/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (12,'로맨스영화_포스터_어느멋진아침.jpg','로맨스영화_상세1_어느멋진아침.jpg','로맨스영화_상세2_어느멋진아침.jpg','로맨스영화_상세3_어느멋진아침.jpg','로맨스영화_상세4_어느멋진아침.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (17,'공포,스릴러영화_포스터_이노센트.jpg','공포,스릴러영화_상세1_이노센트.jpg','공포,스릴러영화_상세2_이노센트.jpg','공포,스릴러영화_상세3_이노센트.jpg','공포,스릴러영화_상세4_이노센트.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (20,'그림전시_포스터_라울 뒤피.jpg','그림전시_상세1_라울 뒤피.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (21,'연극공연_상세1_한뼘사이.jpg','연극공연_상세2_한뼘사이.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (31,'공포,스릴러영화_포스터_인시디어스빨간문.jpg','공포,스릴러영화_상세1_인시디어스빨간문.jpg','공포,스릴러영화_상세2_인시디어스빨간문.jpg','공포,스릴러영화_상세3_인시디어스빨간문.jpg','공포,스릴러영화_상세4_인시디어스빨간문.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (48,'로맨스영화_포스터_거룩한 술꾼의 전설.jpg','로맨스영화_상세1_거룩한 술꾼의 전설.jpg','로맨스영화_상세2_거룩한 술꾼의 전설.jpg','로맨스영화_상세3_거룩한 술꾼의 전설.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (60,'뮤지컬공연_포스터_가요톱텐.jpg','뮤지컬공연_상세1_가요톱텐.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (78,'코미디영화_포스터_해적.jpg','코미디영화_상세1_해적.jpg','코미디영화_상세2_해적.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (86,'코미디영화_포스터_도라에몽.jpg','코미디영화_상세1_도라에몽.jpg','코미디영화_상세2_도라에몽.jpg','코미디영화_상세3_도라에몽.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (95,'클래식공연_포스터_지브리 WITH 샌드아트 IN 부산.jpg','클래식공연_상세1_지브리 WITH 샌드아트 IN 부산.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (96,'코미디영화_포스터_마야3.jpg','코미디영화_상세1_마야3.jpg','코미디영화_상세2_마야3.jpg','코미디영화_상세3_마야3.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (99,'클래식공연_포스터_2023 디즈니 인 콘서트.jpg','클래식공연_상세1_2023 디즈니 인 콘서트.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (104,'클래식공연_포스터_요요 마 첼로 리사이틀.jpg','클래식공연_상세1_요요 마 첼로 리사이틀.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (123,'그림전시_포스터_제이디 차_구미호 혹은 우리를 호리는 것들 이야기.jpg','그림전시_상세1_제이디 차_구미호 혹은 우리를 호리는 것들 이야기.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (125,'그림전시_포스터_앤서니 브라운의 행복극장展-광주.jpg','그림전시_상세1_앤서니 브라운의 행복극장展-광주.jpg','그림전시_상세2_앤서니 브라운의 행복극장展-광주.jpg','그림전시_상세3_앤서니 브라운의 행복극장展-광주.jpg','작품전시_상세4_앤서니 브라운의 행복극장展-광주.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (132,'그림전시_포스터_2023 이세계 페스티벌.jpg','그림전시_상세1_2023 이세계 페스티벌.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (133,'그림전시_포스터_[최대30%할인] 빛의 시어터 8월 핫썸머 특가.jpg','그림전시_상세1_[최대30%할인] 빛의 시어터 8월 핫썸머 특가.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (134,'그림전시_포스터_미구엘 슈발리에 디지털 뷰티 SEASON2.jpg','그림전시_상세1_미구엘 슈발리에 디지털 뷰티 SEASON2.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (138,'그림전시_포스터_K-푸드페스타 in 서울 2023.jpg','그림전시_상세1_K-푸드페스타 in 서울 2023.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (139,'그림전시_포스터_2023 캠핑페스타 FW시즌 수원.jpg','그림전시_상세1_2023 캠핑페스타 FW시즌 수원.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (142,'그림전시_포스터_대화의 방식.jpg','그림전시_포스터_대화의 방식.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (145,'사진전시_포스터_2023 소장품 기획전회화 아닌(Not Paintings).JPG','사진전시_포스터_2023 소장품 기획전회화 아닌(Not Paintings).JPG',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (148,'사진전시_포스터_''신디셔먼 온 스테이지- 파트2 컬렉션 소장품 사진전.jpg','사진전시_상세1_''신디셔먼 온 스테이지- 파트2 컬렉션 소장품 사진전.jpg','사진전시_상세2_''신디셔먼 온 스테이지- 파트2 컬렉션 소장품 사진전.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (18,'그림전시_포스터_거장의 시선,사람을 향하다. 영국내셔널갤러리명화전.jpg','그림전시_상세1_거장의 시선,사람을 향하다. 영국내셔널갤러리명화전.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (22,'그림전시_포스터_동물 없는 동물원 展.jpg','그림전시_상세1_동물 없는 동물원 展.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (24,'그림전시_포스터_앙리 마티스 _ 라이프 앤 조이.jpg','그림전시_상세1_앙리 마티스 _ 라이프 앤 조이.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (26,'연극공연_포스터_택시안에서.jpg','연극공연_상세1_택시안에서.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (27,'그림전시_포스터_데이비드 호크니 & 브리티쉬 팝 아트 부산.jpg','그림전시_상세1_데이비드 호크니 & 브리티쉬 팝 아트 부산.jpg','그림전시_상세2_데이비드 호크니 & 브리티쉬 팝 아트 부산.jpg','그림전시_상세3_데이비드 호크니 & 브리티쉬 팝 아트 부산.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (38,'로맨스영화_포스터_겨울왕국2.jpg','로맨스영화_상세1_겨울왕국2.jpg','로맨스영화_상세2_겨울왕국2.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (40,'연극공연_포스터_가장보통의연애.jpg','연극공연_상세1_가장보통의연애.jpg','연극공연_상세2_가장보통의연애.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (56,'뮤지컬공연_포스터_삼총사.jpg','뮤지컬공연_상세1_삼총사.jpg','뮤지컬공연_상세2_삼총사.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (63,'뮤지컬공연_포스터_22년2개월.jpg','뮤지컬공연_상세1_22년2개월.jpg','뮤지컬공연_상세2_22년2개월.jpg','뮤지컬공연_상세3_22년2개월.jpg','뮤지컬공연_상세4_22년2개월.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (66,'공포,스릴러영화_포스터_그녀의 취미생활.jpg','공포,스릴러영화_상세1_그녀의 취미생활.jpg','공포,스릴러영화_상세2_그녀의 취미생활.jpg','공포,스릴러영화_상세3_그녀의 취미생활.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (68,'공포,스릴러영화_포스터_잠.jpg','공포,스릴러영화_상세1_잠.jpg','공포,스릴러영화_상세2_잠.jpg','공포,스릴러영화_상세3_잠.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (70,'공포,스릴러영화_포스터_신체모음집.jpg','공포,스릴러영화_상세1_신체모음집.jpg','공포,스릴러영화_상세2_신체모음집.jpg','공포,스릴러영화_상세3_신체모음집.jpg','공포,스릴러영화_상세4_신체모음집.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (71,'콘서트공연_포스터_엑스트라 오디너리 콘서트.jpg','콘서트공연_상세1_엑스트라 오디너리 콘서트.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (72,'공포,스릴러영화_포스터_메가로돈2.jpg','공포,스릴러영화_상세1_메가로돈2.jpg','공포,스릴러영화_상세2_메가로돈2.jpg','공포,스릴러영화_상세3_메가로돈2.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (79,'콘서트공연_포스터_레트로슈퍼콘서트.jpg','콘서트공연_상세1_레트로슈퍼콘서트.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (90,'코미디영화_포스터_강변의 무코리타.jpg','코미디영화_상세1_강변의 무코리타.jpg','코미디영화_상세2_강변의 무코리타.jpg','코미디영화_상세3_강변의 무코리타.jpg','코미디영화_상세4_강변의 무코리타.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (94,'코미디영화_포스터_바비.jpg','코미디영화_상세1_바비.jpg','코미디영화_상세2_바비.jpg','코미디영화_상세3_바비.jpg','코미디영화_상세4_바비.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (100,'액션영화_포스터_슬램덩크.jpg','액션영화_상세1_슬램덩크.jpg','액션영화_상세2_슬램덩크.jpg','액션영화_상세3_슬램덩크.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (108,'클래식공연_포스터_정트리오 콘서트.png','클래식공연_상세1_정트리오 콘서트.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (116,'클래식공연_포스터_광주시립교향악단 2023 송년음악회.jpg','클래식공연_상세1_매일클래식과 함께하는 엘콘서트.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (119,'클래식공연_포스터_지브리를 품은 클래식.jpg','클래식공연_상세1_지브리를 품은 클래식.jpg','클래식공연_상세2_지브리를 품은 클래식.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (131,'그림전시_포스터_[부산] 상상을 찍는 작가 에릭 요한슨展.jpg','그림전시_상세1_[부산] 상상을 찍는 작가 에릭 요한슨展.jpg','그림전시_상세2_[부산] 상상을 찍는 작가 에릭 요한슨展.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (141,'그림전시_포스터_헤더윅 스튜디오.jpg','그림전시_상세1_헤더윅 스튜디오.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (143,'그림전시_포스터_시선과 자세.jpg','그림전시_포스터_시선과 자세.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (144,'사진전시_포스터_출구가어디예요.JPG','사진전시_포스터_출구가어디예요.JPG',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (146,'사진전시_포스터_2023 제9회 대구사진비엔날레_다시 사진으로!.jpg','사진전시_포스터_2023 제9회 대구사진비엔날레_다시 사진으로!.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (149,'사진전시_포스터_관계의 기록, 풍경으로의 건축.jpg','사진전시_상세1_관계의 기록, 풍경으로의 건축.JPG','사진전시_상세2_관계의 기록, 풍경으로의 건축.JPG',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (151,'사진전시_포스터_제이알 _크로니클스.jpg','사진전시_상세1_제이알_ 크로니클스.jpg','사진전시_상세2_제이알_ 크로니클스.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (1,'작품전시_포스터_제10회 광주디자인비엔날레.jpg','작품전시_상세1_제10회 광주디자인비엔날레.jpg','작품전시_상세2_제10회 광주디자인비엔날레.jpg','작품전시_상세3_제10회 광주디자인비엔날레.jpg','작품전시_상세4_제10회 광주디자인비엔날레.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (2,'액션영화_포스터_잔고.png','액션영화_상세1_잔고.PNG','액션영화_상세2_잔고.PNG','액션영화_상세3_잔고.PNG','액션영화_상세4_잔고.png',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (4,'작품전시_포스터_국립중앙박물관 특별전 ''영원한 여정, 특별한 동행''.jpg','작품전시_상세1_국립중앙박물관 특별전 ''영원한 여정, 특별한 동행''.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (19,'연극공연_포스터_행오버.jpg','연극공연_상세1_행오버.jpg','연극공연_상세2_행오버.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (23,'로맨스영화_포스터_안녕,내일또만나.jpg','로맨스영화_상세1_안녕,내일또만나.jpg','로맨스영화_상세2_안녕,내일또만나.jpg','로맨스영화_상세3_안녕,내일또만나.jpg','로맨스영화_상세4_안녕,내일또만나.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (25,'그림전시_포스터_2023전남국제수묵비엔날레.jpg','그림전시_상세1_2023전남국제수묵비엔날레.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (29,'연극공연_포스터_진짜나쁜소녀.jpg','연극공연_상세1_진짜나쁜소녀.jpg','연극공연_상세2_진짜나쁜소녀.jpg','연극공연_상세3_진짜나쁜소녀.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (30,'로맨스영화_포스터_알라딘.jpg','로맨스영화_상세1_알라딘.jpg','로맨스영화_상세2_알라딘.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (35,'연극공연_포스터_사춘기 메들리.jpg','연극공연_상세1_사춘기 메들리.jpg','연극공연_상세2_사춘기 메들리.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (36,'로맨스영화_포스터_아바타.jpg','로맨스영화_상세1_아바타.jpg','로맨스영화_상세2_아바타.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (44,'로맨스영화_포스터_엔니오.jpg','로맨스영화_상세1_엔니오.jpg','로맨스영화_상세2_엔니오.jpg','로맨스영화_상세3_엔니오.jpg','로맨스영화_상세4_엔니오.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (45,'뮤지컬공연_포스터_후크.jpg','뮤지컬공연_상세1_후크.jpg','뮤지컬공연_상세2_후크.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (46,'공포,스릴러영화_포스터_부기맨.jpg','공포,스릴러영화_상세1_부기맨.jpg','공포,스릴러영화_상세2_부기맨.jpg','공포,스릴러영화_상세3_부기맨.jpg','공포,스릴러영화_상세4_부기맨.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (47,'뮤지컬공연_포스터_타오르는 어둠 속에서.jpg','뮤지컬공연_상세1_타오르는 어둠 속에서.jpg','뮤지컬공연_상세2_타오르는 어둠 속에서.jpg','뮤지컬공연_상세3_타오르는 어둠 속에서.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (49,'뮤지컬공연_포스터_위윌락유.jpg','뮤지컬공연_상세1_위윌락유.jpg','뮤지컬공연_상세2_위윌락유.jpg','뮤지컬공연_상세3_위윌락유.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (50,'로맨스영화_포스터_시맨틱에러 더무비.jpg','로맨스영화_상세1_시맨틱에러 더무비.jpg','로맨스영화_상세2_시맨틱에러 더무비.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (53,'뮤지컬공연_포스터_와일드그레이.jpg','뮤지컬공연_상세1_와일드그레이.jpg','뮤지컬공연_상세2_와일드그레이.jpg','뮤지컬공연_상세3_와일드그레이.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (67,'콘서트공연_포스터_포크트리오 동창회.jpg','콘서트공연_상세1_포크트리오 동창회.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (69,'콘서트공연_포스터_미모리스즈코 팬미팅.jpg','콘서트공연_상세1_미모리스즈코 팬미팅.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (75,'콘서트공연_포스터_어게인스트 더 커런트 라이브 인서울 2023.png','콘서트공연_상세1_어게인스트 더 커런트 라이브 인 서울 2023.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (80,'코미디영화_포스터_과속스캔들.jpg','코미디영화_상세1_과속스캔들.jpg','코미디영화_상세2_과속스캔들.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (82,'콘서트공연_포스터_이상한 이승환.jpg','콘서트공연_상세1_이상한 이승환.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (87,'콘서트공연_포스터_2023 어스어스 페스티벌.jpg','콘서트공연_상세1_2023 어스어스 페스티벌.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (89,'콘서트공연_포스터_Someday Festival 2023.jpg','콘서트공연_상세1_Someday Festival 2023.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (101,'액션영화_포스터_비공식작전.jpg','액션영화_상세1_비공식작전.jpg','액션영화_상세2_비공식작전.jpg','액션영화_상세3_비공식작전.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (105,'액션영화_포스터_볼코노고프 대위 탈출하다.jpg','액션영화_상세1_볼코노고프 대위 탈출하다.jpg','액션영화_상세2_볼코노고프 대위 탈출하다.jpg','액션영화_상세3_볼코노고프 대위 탈출하다.jpg','액션영화_상세4_볼코노고프 대위 탈출하다.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (106,'클래식공연_포스터_푸치니 투란토드.jpg','클래식공연_상세1_푸치니 투란토드.jpg','클래식공연_상세2_푸치니 투란토드.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (111,'클래식공연_포스터_매일클래식과 함께하는 엘콘서트.jpg','클래식공연_상세1_매일클래식과 함께하는 엘콘서트.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (112,'클래식공연_포스터_김겨울의 요즘 클래식.jpg','클래식공연_상세1_김겨울의 요즘 클래식.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (113,'액션영화_포스터_더문.jpg','액션영화_상세1_더문.jpg','액션영화_상세2_더문.jpg','액션영화_상세3_더문.jpg','액션영화_상세4_더문.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (117,'액션영화_포스터_보호자.jpg','액션영화_상세1_보호자.jpg','액션영화_상세2_보호자.jpg','액션영화_상세3_보호자.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (120,'액션영화_포스터_명탐정코난-흑철의어영.jpg','액션영화_상세1_명탐정코난-흑철의어영.jpg','액션영화_상세2_명탐정코난-흑철의어영.jpg','액션영화_상세3_명탐정코난-흑철의어영.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (124,'그림전시_포스터_상실의 징후들 _ SIGNS of LOSS - 부산.jpg','그림전시_상세1_상실의 징후들 _ SIGNS of LOSS - 부산.jpg','그림전시_상세2_상실의 징후들 _ SIGNS of LOSS - 부산.jpg','그림전시_상세3_상실의 징후들 _ SIGNS of LOSS - 부산.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (126,'그림전시_포스터_에바 알머슨 특별전 _ 에바 알머슨, Andando(부산).jpg','그림전시_포스터_에바 알머슨 특별전 _ 에바 알머슨, Andando(부산).jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (127,'그림전시_포스터_［얼리버드］ 일리야 밀스타인.JPG','그림전시_상세1_［얼리버드］ 일리야 밀스타인.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (129,'그림전시_포스터_모네 인사이드.JPG','그림전시_상세1_모네 인사이드.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (130,'그림전시_포스터_2023 하반기 경복궁 생과방.jpg','그림전시_상세1_2023 하반기 경복궁 생과방.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (135,'그림전시_포스터_2023 합천 씨파크(C-PARK) - 캠프닉콤마 종일권 오픈 (9월~12월).jpg','그림전시_상세1_2023 합천 씨파크(C-PARK) - 캠프닉콤마 종일권 오픈 (9월~12월).jpg','그림전시_상세2_2023 합천 씨파크(C-PARK) - 캠프닉콤마 종일권 오픈 (9월~12월).jpg','그림전시_상세3_2023 합천 씨파크(C-PARK) - 캠프닉콤마 종일권 오픈 (9월~12월).jpg','그림전시_상세4_2023 합천 씨파크(C-PARK) - 캠프닉콤마 종일권 오픈 (9월~12월).jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (5,'작품전시_포스터_빈센트 발_ ART OF SHADOW(얼리버드).JPG','작품전시_상세1_빈센트 발 _ ART OF SHADOW(얼리버드).jpg','작품전시_상세2_빈센트 발 _ ART OF SHADOW(얼리버드).jpg','작품전시_상세3_빈센트 발 _ ART OF SHADOW(얼리버드).jpg','작품전시_상세4_빈센트 발 _ ART OF SHADOW(얼리버드).jpg','작품전시_상세5_빈센트 발 _ ART OF SHADOW(얼리버드).jpg','/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (6,'작품전시_포스터_강릉 참소리축음기＆에디슨과학박물관.jpg','작품전시_상세1_강릉 참소리축음기＆에디슨과학박물관.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (9,'액션영화_포스터_그란투리스모.png','액션영화_상세1_그란투리스모.png','액션영화_상세2_그란투리스모.png','액션영화_상세3_그란투리스모.png','액션영화_상세4_그란투리스모.png',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (32,'연극공연_상세1_이프온리.jpg','연극공연_상세2_이프온리.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (28,'로맨스영화_포스터_왕의남자.jpg','로맨스영화_상세1_왕의남자.jpg','로맨스영화_상세2_왕의남자.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (33,'로맨스영화_포스터_국제시장.jpg','로맨스영화_상세1_국제시장.jpg','로맨스영화_상세2_국제시장.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (34,'연극공연_포스터_연극라면.jpg','연극공연_상세1_연극라면.jpg','연극공연_상세2_연극라면.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (51,'뮤지컬공연_포스터_우리들의사랑.jpg','뮤지컬공연_상세1_우리들의사랑.jpg','뮤지컬공연_상세3_우리들의사랑.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (57,'뮤지컬공연_포스터_사칠.jpg','뮤지컬공연_상세1_사칠.jpg','뮤지컬공연_상세2_사칠.jpg','뮤지컬공연_상세3_사칠.jpg','뮤지컬공연_상세4_사칠.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (58,'공포,스릴러영화_포스터_범죄도시2.jpg','공포,스릴러영화_상세1_범죄도시2.jpg','공포,스릴러영화_상세2_범죄도시2.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (59,'뮤지컬공연_포스터_문스토리.jpg','뮤지컬공연_상세1_문스토리.jpg','뮤지컬공연_상세2_문스토리.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (73,'콘서트공연_포스터_2023조이올팍페스티벌.jpg','콘서트공연_상세1_2023조이올팍페스티벌.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (74,'공포,스릴러영화_포스터_콘크리트유토피아.jpg','공포,스릴러영화_상세1_콘크리트유토피아.jpg','공포,스릴러영화_상세2_콘크리트유토피아.jpg','공포,스릴러영화_상세3_콘크리트유토피아.jpg','공포,스릴러영화_상세4_콘크리트유토피아.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (76,'공포,스릴러영화_포스터_타겟.jpg','공포,스릴러영화_상세1_타겟.jpg','공포,스릴러영화_상세2_타겟.jpg','공포,스릴러영화_상세3_타겟.jpg','공포,스릴러영화_상세4_타겟.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (77,'콘서트공연_포스터_김창완밴드 콘서트.jpg','콘서트공연_상세1_김창완밴드 콘서트.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (85,'콘서트공연_포스터_2023 변진섭 전국투어 콘서트.jpg','콘서트공연_상세1_2023 변진섭 전국투어 콘서트.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (92,'코미디영화_포스터_조이라이드.jpg','코미디영화_상세1_조이라이드.jpg','코미디영화_상세2_조이라이드.jpg','코미디영화_상세3_조이라이드.jpg','코미디영화_상세4_조이라이드.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (93,'코미디영화_포스터_수상한그녀.jpg','코미디영화_상세1_수상한그녀.jpg','코미디영화_상세2_수상한그녀.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (102,'클래식공연_포스터_폴포츠 내한공연.jpg','클래식공연_상세1_폴포츠 내한공연.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (110,'액션영화_포스터_스파이코드명포춘.jpg','액션영화_상세1_스파이코드명포춘.jpg','액션영화_상세2_스파이코드명포춘.jpg','액션영화_상세3_스파이코드명포춘.jpg','액션영화_상세4_스파이코드명포춘.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (118,'액션영화_포스터_미션임파서블 데드레코닝.jpg','액션영화_상세1_미션임파서블 데드레코닝.jpg','액션영화_상세2_미션임파서블 데드레코닝.jpg','액션영화_상세3_미션임파서블 데드레코닝.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (122,'그림전시_포스터_알폰스 무하 이모션 인 서울.jpg','그림전시_상세1_알폰스 무하 이모션 인 서울.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (128,'그림전시_포스터_동화작가 전이수 특별전시.JPG','그림전시_상세1_동화작가 전이수 특별전시.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (136,'그림전시_포스터_제 1회 강진 하맥축제.jpg','그림전시_상세1_전라남도 강진군 군동면 종합운동장길 60 강진종합운동장.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (137,'그림전시_포스터_2023 대구치맥페스티벌 프리미엄 사전예약존.jpg','그림전시_상세1_2023 대구치맥페스티벌 프리미엄 사전예약존.jpg','그림전시_상세2_2023 대구치맥페스티벌 프리미엄 사전예약존.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (140,'그림전시_포스터_브릭캠퍼스 제주.jpg','그림전시_상세1_브릭캠퍼스 제주.jpg','그림전시_상세2_브릭캠퍼스 제주.jpg','그림전시_상세3_브릭캠퍼스 제주.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (147,'사진전시_포스터_요시다유니alchemy.jpg','사진전시_상세1_요시다유니alchemy.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (150,'사진전시_포스터_이언경 개인 사진전 알리바이 ALIBI 展.jpg','사진전시_포스터_이언경 개인 사진전 알리바이 ALIBI 展.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (7,'공포,스릴러영화_포스터_더리프언더워터.jpg','공포,스릴러영화_상세1_더리프언더워터.jpg','공포,스릴러영화_상세2_더리프언더워터.jpg','공포,스릴러영화_상세3_더리프언더워터.jpg','공포,스릴러영화_상세4_더리프언더워터.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (8,'작품전시_포스터_디자인 가구 컬렉션 “어반베이스전(展)＂.jpg','작품전시_상세1_디자인 가구 컬렉션 “어반베이스전(展)＂.jpg','작품전시_상세2_디자인 가구 컬렉션 “어반베이스전(展)＂.jpg','작품전시_상세3_디자인 가구 컬렉션 “어반베이스전(展)＂.jpg','작품전시_상세4_디자인 가구 컬렉션 “어반베이스전(展)＂.jpg','작품전시_상세5_디자인 가구 컬렉션 “어반베이스전(展)＂.jpg','/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (37,'연극공연_포스터_딜리버리.jpg','연극공연_상세1_딜리버리.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (39,'연극공연_포스터_당신만이.jpg','연극공연_상세1_당신만이.jpg','연극공연_상세2_당신만이.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (41,'로맨스영화_포스터_스즈메의 문단속.jpg','로맨스영화_상세1_스즈메의 문단속.jpg','로맨스영화_상세2_스즈메의 문단속.jpg','로맨스영화_상세3_스즈메의 문단속.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (42,'공포,스릴러영화_포스터_샤이닝.jpg','공포,스릴러영화_상세1_샤이닝.jpg','공포,스릴러영화_상세2_샤이닝.jpg','공포,스릴러영화_상세3_샤이닝.jpg','공포,스릴러영화_상세4_샤이닝.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (43,'로맨스영화_포스터_아버지의 마음.jpg','로맨스영화_상세1_아버지의 마음.jpg','로맨스영화_상세2_아버지의 마음.jpg','로맨스영화_상세3_아버지의 마음.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (52,'로맨스영화_포스터_엘리멘탈.jpg','로맨스영화_상세1_엘리멘탈.jpg','로맨스영화_상세2_엘리멘탈.jpg','로맨스영화_상세3_엘리멘탈.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (54,'로맨스영화_포스터_달짝지근해.jpg','로맨스영화_상세1_달짝지근해.jpg','로맨스영화_상세2_달짝지근해.jpg','로맨스영화_상세3_달짝지근해.jpg','로맨스영화_상세4_달짝지근해.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (55,'뮤지컬공연_포스터_아킬레스.jpg','뮤지컬공연_상세1_아킬레스.jpg','뮤지컬공연_상세2_아킬레스.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (61,'공포,스릴러영화_포스터_지옥만세.jpg','공포,스릴러영화_상세1_지옥만세.jpg','공포,스릴러영화_상세2_지옥만세.jpg','공포,스릴러영화_상세3_지옥만세.jpg','공포,스릴러영화_상세4_지옥만세.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (62,'뮤지컬공연_포스터_23별주부전.jpg','뮤지컬공연_상세1_23별주부전.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (64,'연극공연_포스터_혜영에게.jpg','연극공연_상세1_혜영에게.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (65,'연극공연_포스터_괴담.jpg','연극공연_상세1_괴담.jpg','연극공연_상세2_괴담.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (81,'코미디영화_포스터_엑시트.jpg','코미디영화_상세1_엑시트.jpg','코미디영화_상세2_엑시트.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (83,'콘서트공연_포스터_전율 정동하X소향.jpg','콘서트공연_상세1_전율 정동하X소향.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (84,'코미디영화_포스터_몬스터패밀리2.jpg','코미디영화_상세1_몬스터패밀리2.jpg','코미디영화_상세2_몬스터패밀리2.jpg','코미디영화_상세3_몬스터패밀리2.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (88,'코미디영화_포스터_핑크퐁.jpg','코미디영화_상세1_핑크퐁.jpg','코미디영화_상세2_핑크퐁.jpg','코미디영화_상세3_핑크퐁.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (91,'코미디영화_포스터_물꽃의 전설.jpg','코미디영화_상세1_물꽃의 전설.jpg','코미디영화_상세2_물꽃의 전설.jpg','코미디영화_상세3_물꽃의 전설.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (97,'클래식공연_포스터_지브리 페스티벌.jpg','클래식공연_상세1_지브리 페스티벌.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (98,'코미디영화_포스터_극한직업.jpg','코미디영화_상세1_극한직업.webp','코미디영화_상세2_극한직업.jpg',null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (103,'액션영화_포스터_런닝맨.jpg','액션영화_상세1_런닝맨.jpg','액션영화_상세2_런닝맨.jpg','액션영화_상세3_런닝맨.jpg','액션영화_상세4_런닝맨.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (107,'액션영화_포스터_해리포터와 혼혈왕자.jpg','액션영화_상세1_해리포터와 혼혈왕자.jpg','액션영화_상세2_해리포터와 혼혈왕자.jpg','액션영화_상세3_해리포터와 혼혈왕자.jpg',null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (109,'액션영화_포스터_밀수.jpg','액션영화_상세1_밀수.jpg','액션영화_상세2_밀수.jpg','액션영화_상세3_밀수.jpg','액션영화_상세4_밀수.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (114,'클래식공연_포스터_클래식 판타지아 대구.jpg','클래식공연_상세1_클래식 판타지아 대구.jpg','클래식공연_상세2_클래식 판타지아 대구.jpg','클래식공연_상세3_클래식 판타지아 대구.jpg','클래식공연_상세4_클래식 판타지아 대구.jpg',null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (115,'액션영화_포스터_오펜하이머.jpg','액션영화_상세1_오펜하이머.jpg','액션영화_상세2_오펜하이머.jpg','액션영화_상세3_오펜하이머.jpg','액션영화_상세4_오펜하이머.jpg','액션영화_상세5_오펜하이머.jpg','/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (11,'작품전시_포스터_한국만화박물관 입장권.jpg','작품전시_상세1_한국만화박물관 입장권.jpg',null,null,null,null,'/resource/product-upfiles');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (13,'작품전시_포스터_백남준 X 베르나르뷔페_ 히스토릭 메모리.jpg','작품전시_상세1_백남준 X 베르나르뷔페_ 히스토릭 메모리.jpg','작품전시_상세2_백남준 X 베르나르뷔페_ 히스토릭 메모리.jpg',null,null,null,'C:\Users\user1\Desktop\team-semi-new\team-semi-new\team-semi-new\src\main\webapp\resources\product_upfiles\');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (14,'작품전시_포스터_아트로드 특별전시 2023 _ 아트원정대 붓 들고 세계로.jpg','작품전시_상세1_아트로드 특별전시 2023 _ 아트원정대 붓 들고 세계로.jpg',null,null,null,null,'C:\Users\user1\Desktop\team-semi-new\team-semi-new\team-semi-new\src\main\webapp\resources\product_upfiles\');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (15,'작품전시_포스터_이달의 소장품_ 빈랑 용기(Pekinangan).jpg','작품전시_상세1_이달의 소장품_ 빈랑 용기(Pekinangan).jpg',null,null,null,null,'C:\Users\user1\Desktop\team-semi-new\team-semi-new\team-semi-new\src\main\webapp\resources\product_upfiles\');
Insert into TICKET.PRODUCT_IMG (PRODUCT_NO,POSTER_NAME,DETAIL1_NAME,DETAIL2_NAME,DETAIL3_NAME,DETAIL4_NAME,DETAIL5_NAME,IMAGE_PATH) values (16,'작품전시_포스터_Asia Culture Museum Permanent Exhibitions.jpg','작품전시_상세1_Asia Culture Museum Permanent Exhibitions.jpg','작품전시_상세2_Asia Culture Museum Permanent Exhibitions.jpg',null,null,null,'C:\Users\user1\Desktop\team-semi-new\team-semi-new\team-semi-new\src\main\webapp\resources\product_upfiles\');
--------------------------------------------------------
--  DDL for Index PK_PRODUCT_IMG
--------------------------------------------------------

  CREATE UNIQUE INDEX "TICKET"."PK_PRODUCT_IMG" ON "TICKET"."PRODUCT_IMG" ("PRODUCT_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table PRODUCT_IMG
--------------------------------------------------------

  ALTER TABLE "TICKET"."PRODUCT_IMG" ADD CONSTRAINT "PK_PRODUCT_IMG" PRIMARY KEY ("PRODUCT_NO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT_IMG
--------------------------------------------------------

  ALTER TABLE "TICKET"."PRODUCT_IMG" ADD CONSTRAINT "FK_PRODUCT_NO_IMG" FOREIGN KEY ("PRODUCT_NO")
	  REFERENCES "TICKET"."PRODUCT" ("PRODUCT_NO") ENABLE;
