SELECT USER_NAME, C.CATEGORY_NAME, D.CATEGORY_NAME, E.CATEGORY_NAME
FROM USER_INFO
JOIN CATEGORY_INFO C ON (INTEREST_MOVIE = C.CATEGORY_TYPE)
JOIN CATEGORY_INFO D ON (INTEREST_DISPLAY = D.CATEGORY_TYPE)
JOIN CATEGORY_INFO E ON (INTEREST_SHOW = E.CATEGORY_TYPE);

SELECT PRODUCT_NO, PRODUCT_TITLE, LOCAL_NO
from product
;

-- ·Î±×ÀÎ ¸â¹ö ¸Í±×·ç 
SELECT
       USER_NO
     , USER_ID
     , USER_PWD
     , USER_NAME
     , USER_BIRTH
     , C.CATEGORY_NAME
     , D.CATEGORY_NAME
     , E.CATEGORY_NAME
     , EMAIL
     , PHONE
     , GRADE_NAME
     , STATUS
  FROM USER_INFO
  JOIN CATEGORY_INFO C ON (INTEREST_MOVIE = C.CATEGORY_TYPE)
  JOIN CATEGORY_INFO D ON (INTEREST_DISPLAY = D.CATEGORY_TYPE)
  JOIN CATEGORY_INFO E ON (INTEREST_SHOW = E.CATEGORY_TYPE)
  JOIN GRADE G USING(GRADE_NO)
 WHERE USER_ID = ?
   AND USER_PWD = ?
   AND STATUS = 'Y'
   
   
;