INSERT INTO USER_INFO VALUES (SEQ_UNO.NEXTVAL, 'admin', '1234', '관리자', '990101', 2, 6, 11, null, null, 5);

INSERT INTO CONTENT_INFO VALUES (SEQ_CNO.NEXTVAL, '로맨스');
INSERT INTO CONTENT_INFO VALUES (SEQ_CNO.NEXTVAL, '공포/스릴러');
INSERT INTO CONTENT_INFO VALUES (SEQ_CNO.NEXTVAL, '코미디');
INSERT INTO CONTENT_INFO VALUES (SEQ_CNO.NEXTVAL, '액션');
INSERT INTO CONTENT_INFO VALUES (SEQ_CNO.NEXTVAL, '그림전시');
INSERT INTO CONTENT_INFO VALUES (SEQ_CNO.NEXTVAL, '작품전시');
INSERT INTO CONTENT_INFO VALUES (SEQ_CNO.NEXTVAL, '사진전시');
INSERT INTO CONTENT_INFO VALUES (SEQ_CNO.NEXTVAL, '체험전시');
INSERT INTO CONTENT_INFO VALUES (SEQ_CNO.NEXTVAL, '뮤지컬');
INSERT INTO CONTENT_INFO VALUES (SEQ_CNO.NEXTVAL, '연극');
INSERT INTO CONTENT_INFO VALUES (SEQ_CNO.NEXTVAL, '클래식');
INSERT INTO CONTENT_INFO VALUES (SEQ_CNO.NEXTVAL, '콘서트');

INSERT INTO LEVEL_INFO VALUES (SEQ_LNO.NEXTVAL, '전체 관람가');
INSERT INTO LEVEL_INFO VALUES (SEQ_LNO.NEXTVAL, '7세 관람가');
INSERT INTO LEVEL_INFO VALUES (SEQ_LNO.NEXTVAL, '12세 관람가');
INSERT INTO LEVEL_INFO VALUES (SEQ_LNO.NEXTVAL, '15세 관람가');
INSERT INTO LEVEL_INFO VALUES (SEQ_LNO.NEXTVAL, '19세 관람가');

INSERT INTO GRADE VALUES (SEQ_GNO.NEXTVAL, '아이언');
INSERT INTO GRADE VALUES (SEQ_GNO.NEXTVAL, '브론즈');
INSERT INTO GRADE VALUES (SEQ_GNO.NEXTVAL, '실버');
INSERT INTO GRADE VALUES (SEQ_GNO.NEXTVAL, '골드');
INSERT INTO GRADE VALUES (SEQ_GNO.NEXTVAL, '마스터');

INSERT INTO PRODUCT VALUES (SEQ_PNO.NEXTVAL, 1, '어바웃타임', 'CGV 동대문', '23/08/15', '23/12/25', 4, 120, 15000);

SELECT USER_NAME, C.CONTENT_NAME, D.CONTENT_NAME, E.CONTENT_NAME
FROM USER_INFO
JOIN CONTENT_INFO C ON (INTEREST_MOVIE = C.CONTENT_TYPE)
JOIN CONTENT_INFO D ON (INTEREST_DISPLAY = D.CONTENT_TYPE)
JOIN CONTENT_INFO E ON (INTEREST_SHOW = E.CONTENT_TYPE);