-- 드롭

-- 상품이미지 테이블
DROP TABLE PRODUCT_IMG;
-- 상영정보 테이블
DROP TABLE SCREENING_INFO;
-- 예매정보 테이블
DROP TABLE BOOKED_INFO;
-- 카드종류 테이블
DROP TABLE CARD;
-- 결제수단 테이블
DROP TABLE PAYMENT;
-- 리뷰 테이블
DROP TABLE REVIEW_INFO;
-- 좋아요 테이블
DROP TABLE PRODUCT_LIKE;
-- 상품테이블
DROP TABLE PRODUCT;
-- Q&A테이블
DROP TABLE QNA;
-- 공지사항 테이블
DROP TABLE NOTICE;
-- 관람등급 테이블
DROP TABLE LEVEL_INFO;
-- 지역(장소) 테이블
DROP TABLE LOCAL_INFO;
-- 유저 테이블
DROP TABLE USER_INFO;
-- 카테고리 테이블
DROP TABLE CATEGORY_INFO;
-- 회원등급 테이블
DROP TABLE GRADE;


-- 상품시퀀스
DROP SEQUENCE SEQ_PNO;
-- 유저시퀀스
DROP SEQUENCE SEQ_UNO;
-- 리뷰시퀀스
DROP SEQUENCE SEQ_RNO;
-- 예매정보 시퀀스
DROP SEQUENCE SEQ_DNO;
-- 공지사항 시퀀스
DROP SEQUENCE SEQ_NNO;
-- Q&A 시퀀스
DROP SEQUENCE SEQ_QNO;

     
-- 등급테이블 생성
CREATE TABLE GRADE
(
  GRADE_NO NUMBER CONSTRAINT PK_GRADE_NO PRIMARY KEY,
  GRADE_NAME VARCHAR2(20) DEFAULT 1,
  GRADE_DISCOUNT NUMBER DEFAULT 0
);
COMMENT ON COLUMN GRADE.GRADE_NO IS '등급번호';
COMMENT ON COLUMN GRADE.GRADE_NAME IS '등급명';
COMMENT ON COLUMN GRADE.GRADE_DISCOUNT IS '등급할인';

-- 카테고리 테이블 생성
CREATE TABLE CATEGORY_INFO
    (
       CATEGORY_TYPE NUMBER CONSTRAINT PK_CATEGORY_INFO_TYPE PRIMARY KEY,
      CATEGORY_NAME VARCHAR2(30) NOT NULL
    ); 
COMMENT ON COLUMN CATEGORY_INFO.CATEGORY_TYPE IS '카테고리타입';
COMMENT ON COLUMN CATEGORY_INFO.CATEGORY_NAME IS '카테고리명';

-- 관람등급 생성
CREATE TABLE LEVEL_INFO
(
  PRODUCT_LEVEL NUMBER CONSTRAINT PK_LEVEL_PRODUCT_INFO PRIMARY KEY,
  LEVEL_NAME VARCHAR2(20) NOT NULL
);
COMMENT ON COLUMN LEVEL_INFO.PRODUCT_LEVEL IS '관람등급번호';
COMMENT ON COLUMN LEVEL_INFO.LEVEL_NAME IS '관람등급명';

-- 공지사항 테이블
CREATE TABLE NOTICE
    (
      NOTICE_NO NUMBER CONSTRAINT PK_NOTICE_NO PRIMARY KEY
    , NOTICE_TITLE VARCHAR(50) NOT NULL
    , NOTICE_CONTENT VARCHAR(500) NOT NULL
    , NOTICE_DATE DATE DEFAULT SYSDATE
    , NOTICE_COUNT NUMBER DEFAULT 0
    , STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
    );
COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지사항 번호';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '공지사항 제목';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '공지사항 내용';
COMMENT ON COLUMN NOTICE.NOTICE_DATE IS '공지사항 작성일';
COMMENT ON COLUMN NOTICE.NOTICE_COUNT IS '공지사항 조회수';
COMMENT ON COLUMN NOTICE.STATUS IS '삭제여부(Y/N)';



-- 유저 생성 
CREATE TABLE USER_INFO
    (
      USER_NO NUMBER CONSTRAINT PK_USER_INFO_NO PRIMARY KEY
    , USER_ID VARCHAR2(20) NOT NULL UNIQUE
    , USER_PWD VARCHAR2(30) NOT NULL
    , USER_NAME VARCHAR2(20) NOT NULL
    , USER_BIRTH VARCHAR2(10) NOT NULL
    , INTEREST_MOVIE NUMBER NOT NULL CONSTRAINT FK_USER_INTEREST_MOVIE REFERENCES CATEGORY_INFO
    , INTEREST_DISPLAY NUMBER NOT NULL CONSTRAINT FK_USER_INTEREST_DISPLAY REFERENCES CATEGORY_INFO
    , INTEREST_SHOW NUMBER NOT NULL CONSTRAINT FK_USER_INTEREST_SHOW REFERENCES CATEGORY_INFO
    , EMAIL VARCHAR2(50)
    , PHONE VARCHAR2(20) NOT NULL
    , GRADE_NO NUMBER DEFAULT 1 CONSTRAINT FK_USER_GRADE_NO REFERENCES GRADE
    , ENROLL_DATE DATE DEFAULT SYSDATE
    , STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
     );
COMMENT ON COLUMN USER_INFO.USER_NO IS '회원번호';
COMMENT ON COLUMN USER_INFO.USER_ID IS '회원아이디';
COMMENT ON COLUMN USER_INFO.USER_PWD IS '회원비밀번호';
COMMENT ON COLUMN USER_INFO.USER_NAME IS '회원명';
COMMENT ON COLUMN USER_INFO.USER_BIRTH IS '생년월일';
COMMENT ON COLUMN USER_INFO.INTEREST_MOVIE IS '관심_영화(1~4)';
COMMENT ON COLUMN USER_INFO.INTEREST_DISPLAY IS '관심_전시(5~8)';
COMMENT ON COLUMN USER_INFO.INTEREST_SHOW IS '관심_공연(9~12)';
COMMENT ON COLUMN USER_INFO.EMAIL IS '이메일';
COMMENT ON COLUMN USER_INFO.PHONE IS '전화번호';
COMMENT ON COLUMN USER_INFO.GRADE_NO IS '회원등급';
COMMENT ON COLUMN USER_INFO.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN USER_INFO.STATUS IS '탈퇴여부(Y,N)';

-- Q&A테이블
CREATE TABLE QNA
    (
      QNA_NO NUMBER CONSTRAINT PK_QNA_NO PRIMARY KEY
    , USER_NO NUMBER NOT NULL CONSTRAINT FK_QNA_USER_NO REFERENCES USER_INFO
    , QNA_TITLE VARCHAR2(50) NOT NULL
    , QNA_CONTENT VARCHAR2(500) NOT NULL
    , QNA_REPLY VARCHAR2(500) NOT NULL
    , QNA_DATE DATE DEFAULT SYSDATE
    , STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
    );
COMMENT ON COLUMN QNA.QNA_NO IS 'QNA 번호';
COMMENT ON COLUMN QNA.USER_NO IS '작성자 회원번호';
COMMENT ON COLUMN QNA.QNA_TITLE IS 'QNA 제목';
COMMENT ON COLUMN QNA.QNA_CONTENT IS 'QNA 내용';
COMMENT ON COLUMN QNA.QNA_REPLY IS '답변내용';
COMMENT ON COLUMN QNA.QNA_DATE IS '작성날짜';
COMMENT ON COLUMN QNA.STATUS IS '삭제여부(Y/N)';

-- 지역 생성   
CREATE TABLE LOCAL_INFO
     (
       LOCAL_NO NUMBER NOT NULL CONSTRAINT PK_LOCAL_INFO_NO PRIMARY KEY
     , LOCAL_TITLE VARCHAR2(50) NOT NULL
     );   
     
COMMENT ON COLUMN LOCAL_INFO.LOCAL_NO IS '지역번호';
COMMENT ON COLUMN LOCAL_INFO.LOCAL_TITLE IS '지역명';
    
-- 상품 생성
CREATE TABLE PRODUCT 
    (
      PRODUCT_NO NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY
    , CATEGORY_TYPE NUMBER NOT NULL CONSTRAINT FK_PRODUCT_CATEGORY_TYPE REFERENCES CATEGORY_INFO
    , PRODUCT_TITLE VARCHAR2(300) NOT NULL
    , LOCAL_NO NUMBER  CONSTRAINT FK_PRODUCT_LOCAL_NO REFERENCES LOCAL_INFO
    , ADDRESS VARCHAR2(1000) NOT NULL
    , START_PERIOD DATE NOT NULL
    , END_PERIOD DATE NOT NULL
    , PRODUCT_LEVEL NUMBER NOT NULL CONSTRAINT FK_PRODUCT_LEVEL_INFO REFERENCES LEVEL_INFO
    , RUN_TIME NUMBER NOT NULL
    , PRICE NUMBER NOT NULL
    );
COMMENT ON COLUMN PRODUCT.PRODUCT_NO IS '상품번호';
COMMENT ON COLUMN PRODUCT.CATEGORY_TYPE IS '카테고리타입';
COMMENT ON COLUMN PRODUCT.PRODUCT_TITLE IS '상품명';
COMMENT ON COLUMN PRODUCT.LOCAL_NO IS '지역번호';
COMMENT ON COLUMN PRODUCT.ADDRESS IS '상세주소';
COMMENT ON COLUMN PRODUCT.START_PERIOD IS '시작날짜';
COMMENT ON COLUMN PRODUCT.END_PERIOD IS '종료날짜';
COMMENT ON COLUMN PRODUCT.PRODUCT_LEVEL IS '관람등급';
COMMENT ON COLUMN PRODUCT.RUN_TIME IS '상영시간';
COMMENT ON COLUMN PRODUCT.PRICE IS '가격';

-- 좋아요 테이블
CREATE TABLE PRODUCT_LIKE
    (
      PRODUCT_NO NUMBER CONSTRAINT FK_PRODUCT_LIKE_NO REFERENCES PRODUCT
    , USER_NO NUMBER CONSTRAINT FK_PRODUCT_USER_LIKE_NO REFERENCES USER_INFO
    , CONSTRAINT PK_PRODUCT_LIKE PRIMARY KEY (PRODUCT_NO, USER_NO)
    );
COMMENT ON COLUMN PRODUCT_LIKE.PRODUCT_NO IS '상품번호';
COMMENT ON COLUMN PRODUCT_LIKE.USER_NO IS '회원번호';

-- 상영정보 테이블
CREATE TABLE SCREENING_INFO
    (
      PRODUCT_NO NUMBER CONSTRAINT FK_SCREENING_NO_INFO REFERENCES PRODUCT
    , SCREENING_DATE DATE NOT NULL
    , SCREENING_DAY_TIME CHAR(1)  DEFAULT 'N' CHECK(SCREENING_DAY_TIME IN('Y','N') )
    , SCREENING_NIGHT_TIME CHAR(1) DEFAULT 'N' CHECK(SCREENING_NIGHT_TIME IN('Y','N') )
    , SCREENING_DAY_SEAT NUMBER DEFAULT 0
    , SCREENING_NIGHT_SEAT NUMBER DEFAULT 0
    );        
COMMENT ON COLUMN SCREENING_INFO.PRODUCT_NO IS '상품번호';
COMMENT ON COLUMN SCREENING_INFO.SCREENING_DATE IS '해당날짜';
COMMENT ON COLUMN SCREENING_INFO.SCREENING_DAY_TIME IS '오전(Y/N)';
COMMENT ON COLUMN SCREENING_INFO.SCREENING_NIGHT_TIME IS '오후(Y/N)';
COMMENT ON COLUMN SCREENING_INFO.SCREENING_DAY_SEAT IS '오전잔여좌석';
COMMENT ON COLUMN SCREENING_INFO.SCREENING_NIGHT_SEAT IS '오후잔여좌석';

-- 상품이미지 테이블
CREATE TABLE PRODUCT_IMG
(
 PRODUCT_NO NUMBER CONSTRAINT FK_PRODUCT_NO_IMG REFERENCES PRODUCT CONSTRAINT PK_PRODUCT_IMG PRIMARY KEY,
 POSTER_NAME VARCHAR2(300),
 DETAIL1_NAME VARCHAR2(300),
 DETAIL2_NAME VARCHAR2(300),
 DETAIL3_NAME VARCHAR2(300),
 DETAIL4_NAME VARCHAR2(300),
 DETAIL5_NAME VARCHAR2(300),
 IMAGE_PATH VARCHAR2(1000) DEFAULT 'resource/product-upfiles'
);
COMMENT ON COLUMN PRODUCT_IMG.PRODUCT_NO IS '상품번호';
COMMENT ON COLUMN PRODUCT_IMG.POSTER_NAME IS '포스터 이름';
COMMENT ON COLUMN PRODUCT_IMG.DETAIL1_NAME IS '상세1 이름';
COMMENT ON COLUMN PRODUCT_IMG.DETAIL2_NAME IS '상세2 이름';
COMMENT ON COLUMN PRODUCT_IMG.DETAIL3_NAME IS '상세3 이름';
COMMENT ON COLUMN PRODUCT_IMG.DETAIL4_NAME IS '상세4 이름';
COMMENT ON COLUMN PRODUCT_IMG.DETAIL5_NAME IS '상세5 이름';
COMMENT ON COLUMN PRODUCT_IMG.IMAGE_PATH IS '이미지 경로';

-- 결제수단 테이블
CREATE TABLE PAYMENT
(
    PAYMENT_NO NUMBER CONSTRAINT PK_PAYMENT PRIMARY KEY,
    PAYMENT_NAME VARCHAR2(20) NOT NULL
);
COMMENT ON COLUMN PAYMENT.PAYMENT_NO IS '결제수단 번호';
COMMENT ON COLUMN PAYMENT.PAYMENT_NAME IS '결제수단명';

-- 카드 종류 테이블
CREATE TABLE CARD
(
    CARD_NO NUMBER CONSTRAINT PK_CARD PRIMARY KEY,
    CARD_NAME VARCHAR2(20) NOT NULL
);
COMMENT ON COLUMN CARD.CARD_NO IS '카드사번호';
COMMENT ON COLUMN CARD.CARD_NAME IS '카드사명';

-- 예매정보 테이블
CREATE TABLE BOOKED_INFO
 (
  BOOKED_NO NUMBER CONSTRAINT PK_BOOKED_INFO PRIMARY KEY,
  USER_NO NUMBER CONSTRAINT FK_USER_NO REFERENCES USER_INFO,
  PRODUCT_NO NUMBER CONSTRAINT FK_PRODUCT_NO REFERENCES PRODUCT,
  AUDIENCE NUMBER DEFAULT 1,
  PAYMENT NUMBER CONSTRAINT FK_PAYMENT REFERENCES PAYMENT,
  CARD NUMBER CONSTRAINT FK_CARD REFERENCES CARD,
  BOOKED_DATE DATE DEFAULT SYSDATE,
  SCREEN_DATE VARCHAR2(20) NOT NULL,
  SCREEN_TIME VARCHAR2(20) NOT NULL,
  STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
 );
COMMENT ON COLUMN BOOKED_INFO.BOOKED_NO IS '예매번호';
COMMENT ON COLUMN BOOKED_INFO.USER_NO IS '회원번호';
COMMENT ON COLUMN BOOKED_INFO.PRODUCT_NO IS '상품번호';
COMMENT ON COLUMN BOOKED_INFO.AUDIENCE IS '관람인원';
COMMENT ON COLUMN BOOKED_INFO.PAYMENT IS '결제수단';
COMMENT ON COLUMN BOOKED_INFO.CARD IS '카드종류';
COMMENT ON COLUMN BOOKED_INFO.BOOKED_DATE IS '예매날짜';
COMMENT ON COLUMN BOOKED_INFO.SCREEN_DATE IS '관람날짜';
COMMENT ON COLUMN BOOKED_INFO.SCREEN_TIME IS '관람시간';
COMMENT ON COLUMN BOOKED_INFO.STATUS IS '삭제여부(Y/N)';

-- 리뷰 테이블
CREATE TABLE REVIEW_INFO
    (
      REVIEW_NO NUMBER CONSTRAINT PK_REVIEW_INFO_NO PRIMARY KEY
    , BOOKED_NO NUMBER CONSTRAINT FK_REVIEW_BOOKED_NO REFERENCES BOOKED_INFO
    , REVIEW_CONTENT VARCHAR2(300) NOT NULL
    , USER_NO NUMBER CONSTRAINT FK_REVIEW_USER_NO REFERENCES USER_INFO
    , REVIEW_DATE DATE DEFAULT SYSDATE
    , STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
    );
COMMENT ON COLUMN REVIEW_INFO.REVIEW_NO IS '리뷰번호';
COMMENT ON COLUMN REVIEW_INFO.BOOKED_NO IS '예매번호';
COMMENT ON COLUMN REVIEW_INFO.REVIEW_CONTENT IS '리뷰내용';
COMMENT ON COLUMN REVIEW_INFO.USER_NO IS '작성자';
COMMENT ON COLUMN REVIEW_INFO.REVIEW_DATE IS '리뷰작성날짜';
COMMENT ON COLUMN REVIEW_INFO.STATUS IS '삭제여부(Y/N)';




-- 시퀀스 생성

-- 상품시퀀스 -
CREATE SEQUENCE SEQ_PNO
NOCACHE;
-- 유저시퀀스 -
CREATE SEQUENCE SEQ_UNO
NOCACHE;
-- 리뷰시퀀스 -
CREATE SEQUENCE SEQ_RNO
NOCACHE;
-- 예매정보 시퀀스 -
CREATE SEQUENCE SEQ_DNO
NOCACHE;
-- 공지사항 시퀀스 -
CREATE SEQUENCE SEQ_NNO
NOCACHE;
-- Q&A 시퀀스-
CREATE SEQUENCE SEQ_QNO
NOCACHE;

COMMIT;











